# Generated by Django 5.2.7 on 2025-10-24 02:30

import destinations.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('north', '북인도'), ('south', '남인도')], max_length=50, unique=True, verbose_name='지역명')),
                ('description', models.TextField(blank=True, verbose_name='지역 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역 목록',
                'db_table': 'regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, '여행지명은 최소 2자 이상이어야 합니다.')], verbose_name='여행지명')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='영문명')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10, '설명은 최소 10자 이상이어야 합니다.')], verbose_name='설명')),
                ('image', models.ImageField(upload_to='destinations/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), destinations.models.validate_image_size], verbose_name='대표 이미지')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='주소')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='댓글 수')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='destinations.region', verbose_name='지역')),
            ],
            options={
                'verbose_name': '여행지',
                'verbose_name_plural': '여행지 목록',
                'db_table': 'destinations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['region', '-created_at'], name='destination_region__2e0e84_idx'), models.Index(fields=['-likes_count'], name='destination_likes_c_2448bb_idx'), models.Index(fields=['-view_count'], name='destination_view_co_a57f59_idx')],
            },
        ),
    ]
